spring:
  application:
    name: ms-gateway
  profiles:
    default: eureka-on
server:
  port: 4040
security:
  jwt:
    secret-key: bXkgY2xhdmUgZXMgZGVtYXNpYWRvIHNlZ3VyYWFhYSBwYXJhIHRvZG9zc3MhISE=
    expiration-in-minutes: 30
